ci:
  autofix_prs: false

files: ^py/
repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
    - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
