[tool.black]
line-length = 120
indent-width = 4
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  tests/data/
  | profiling/
  | scripts/generate_schema.py  # Uses match syntax
  | .git/
  | .venv/
)
'''

[tool.codespell]
write-changes = false
skip = ".*/venv,.*log,.*/__pycache__"
